Book_Shopping/config/routes.rb
BookShopping::Application.routes.draw do
resources :payments, only: [:new, :create, :index]
  get '/administrators/welcome' => 'administrators#welcome'
  resources :administrators

  get "/login" => "sessions#new"
  post "sessions/create"
  delete "sessions/destroy"
  get "store/index"
  post "store/index"
  post "product/show"
  post "products/new"

  scope '(:locale)' do
    resources :line_items
    resources :carts
    resources :products
    resources :orders
    root 'store#index', as: 'store'
  end
end

Book_Shopping/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BookShopping</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body class="back_for_store">
  <!-- <div style="float:right">
    <%= t('menu.languages.selection') %><%= link_to t('menu.languages.en'), default_url_options %>
    <%= link_to t('menu.languages.ru'), default_url_options %>
  </div> -->
  <div style="margin-top: 50px">
    <div style="Float:Left;"><%= image_tag("logo.jpg", size: "60x50") %></div>
    <div><p style="font-size:42px"><b>Book Shopping</b></p></div>
  </div>
  <hr>

  <div style="float:left; width:250px; background-color:#66aa99;">
    <div id="cart"><%= render @cart %>
    </div>
    <div>
      <ul>
        <li><%= link_to t('main_menu.home') %></li>
        <li><%= link_to t('main_menu.view_books') %></li>
        <li><%= link_to t('main_menu.gallery') %></li>
        <li><%= link_to t('main_menu.about_us') %></li>
        <li><%= link_to t('main_menu.contact_us') %></li>
      </ul>
      <% if session[:admin_id] %>
      <ul>
        <li class="li"><%= link_to 'Home', '/administrators/welcome' %></li>
        <li class="li"><%= link_to 'View Orders', orders_path %></li>
        <li class="li"><%= link_to 'View Products', products_path %></li>
        <li class="li"><%= link_to 'View Users', administrators_path %></li>
        <li class="li"><%= link_to "Sign Out", sessions_destroy_path, method: :delete %></li>
      </ul>
      <% end %>
    </div>
  </div>

  <div style="margin-left:300px;">
    <%= yield %></div>
  </div>
</body>
</html>