Book_Shopping/config/routes.rb
BookShopping::Application.routes.draw do
resources :payments, only: [:new, :create, :index]
  get '/administrators/welcome' => 'administrators#welcome'
  resources :administrators

  get "/login" => "sessions#new"
  post "sessions/create"
  delete "sessions/destroy"
  get "store/index"
  post "store/index"
  post "product/show"
  post "products/new"

  scope '(:locale)' do
    resources :line_items
    resources :carts
    resources :products
    resources :orders
    root 'store#index', as: 'store'
  end
end

Book_Shopping/app/models/administrator.rb
class Administrator < ActiveRecord::Base
  has_secure_password
end

Book_Shopping/app/controllers/administrators_controller.rb
class AdministratorsController < ApplicationController
  before_filter :authorize
  before_filter :cache_chck
  before_action :set_administrator, only: [:show, :edit, :update, :destroy]
  include CreateCart
  before_action :cart_assign

  def index
    @administrators = Administrator.all
  end

  def show
  end

  def new
    @administrator = Administrator.new
  end

  def edit
  end

  def create
    @administrator = Administrator.new(administrator_params)
    respond_to do |format|
      if @administrator.save
        format.html { redirect_to @administrator, notice: 'Administrator was successfully created.' }
        format.json { render action: 'show', status: :created, location: @administrator }
      else
        format.html { render action: 'new' }
        format.json { render json: @administrator.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @administrator.update(administrator_params)
        format.html { redirect_to @administrator, notice: 'Administrator was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @administrator.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @administrator.destroy
    respond_to do |format|
      format.html { redirect_to administrators_url }
      format.json { head :no_content }
    end
  end

  def welcome
    @total_orders = Order.count
  end

  private
    def set_administrator
      @administrator = Administrator.find(params[:id])
    end

    def administrator_params
      params.require(:administrator).permit(:name, :username, :password, :password_confirmation)
    end


end

Book_Shopping/app/helpers/administrators_helper.rb
module AdministratorsHelper
end

Book_Shopping/app/views/administrators/_form.html.erb
<%= form_for(@administrator) do |f| %>
  <% if @administrator.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@administrator.errors.count, "error") %> prohibited this administrator from being saved:</h2>

      <ul>
      <% @administrator.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Book_Shopping/app/views/administrators/edit.html.erb
<h1>Editing administrator</h1>

<%= render 'form' %>

<%= link_to 'Show', @administrator %> |
<%= link_to 'Back', administrators_path %>

Book_Shopping/app/views/administrators/index.html.erb
<h1>Listing administrators</h1>

<table border="1px">
  <thead>
    <tr>
      <th>Name</th>
      <th>Username</th>
      <th colspan="3"></th>

    </tr>
  </thead>

  <tbody>
    <% @administrators.each do |administrator| %>
      <tr>
        <td><%= administrator.name %></td>
        <td><%= administrator.username %></td>
        <td><%= link_to 'Show', administrator %></td>
        <td><%= link_to 'Edit', edit_administrator_path(administrator) %></td>
        <td><%= link_to 'Destroy', administrator, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

Book_Shopping/app/views/administrators/new.html.erb
<h1>New administrator</h1>

<%= render 'form' %>

<%= link_to 'Back', administrators_path %>

Book_Shopping/app/views/administrators/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @administrator.name %>
</p>

<p>
  <strong>Username:</strong>
  <%= @administrator.username %>
</p>

<%= link_to 'Edit', edit_administrator_path(@administrator) %> |
<%= link_to 'Back', administrators_path %>

Book_Shopping/app/views/administrators/welcome.html.erb
<h1>Hello <%= @admin_details.name %></h1>
It's <%= Time.now %>
We have <%= pluralize(@total_orders, "order") %>.<br>

<%= link_to 'Add New Admin', new_administrator_path %>